Repository zrpaplicacoes/node-functional-boilerplate, pull requests merged in 2020-11, with the labels that each got.

#4 chore: add commitizen and commitlint with git hooks
  commitlint.config.js
  package-lock.json
  package.json
Labels: enhancement

#6 docker-compose upgrade and multi-stage build for docker image
  .dockerignore
  .env.example
  Dockerfile
  config/express.js
  config/mongoDb.js
  dev.Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
  src/infra/database/models/index.js
Labels: enhancement

#7 build(deps): upgrade dependencies and audit packages
  .eslintrc.js
  .github/workflows/test.yml
  package-lock.json
  package.json
  specs/unit/domain/hero/Hero.service.spec.js
  src/container.js
  src/domain/hero/Hero.module.js
  src/domain/utils/validate.js
  src/infra/database/models/Hero.js
  src/infra/database/models/index.js
Labels: security

#10 add vscode debugging
  .example.env
  .github/workflows/test.yml
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  Dockerfile
  README.MD
  bin/.gitkeep
  docker-compose.yml
  index.js
  jsconfig.json
  nodemon.json
  package.json
  specs/unit/domain/hero/Hero.service.spec.js
  src/app/application.js
  src/container.js
Labels: documentation, enhancement

#15 docs(README): fix typos
  README.MD
Labels: documentation

#19 Markdownlint Config
  .markdownlintrc
  Dockerfile
  README.MD
  src/domain/hero/Hero.module.js
Labels: documentation, enhancement

#21 chore: add MIT license
  LICENSE
Labels: documentation

#16 feat(infra/loggin/looger.js): Added Winston
  .example.env
  config/index.js
  index.js
  package-lock.json
  package.json
  specs/unit/infra/logging/logger.spec.js
  specs/unit/utils/isDevelopment.spec.js
  src/container.js
  src/infra/logging/logger.js
  src/interfaces/http/handlers/healthCheck.handler.js
  src/interfaces/http/routers/root.router.js
  src/interfaces/http/routers/v1.router.js
  src/interfaces/http/server.js
  src/utils/index.js
  src/utils/isDevelopment.js
Labels: enhancement
